// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wi_crawler;

namespace wi_crawler.Migrations
{
    [DbContext(typeof(CrawlingContext))]
    [Migration("20200101210057_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("wi_crawler.TermIndex", b =>
                {
                    b.Property<string>("Term")
                        .HasColumnType("TEXT");

                    b.HasKey("Term");

                    b.ToTable("TermIndexes");
                });

            modelBuilder.Entity("wi_crawler.Webpage", b =>
                {
                    b.Property<int>("WebpageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermIndexTerm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("WebpageId");

                    b.HasIndex("TermIndexTerm");

                    b.ToTable("Webpages");
                });

            modelBuilder.Entity("wi_crawler.Webpage", b =>
                {
                    b.HasOne("wi_crawler.TermIndex", null)
                        .WithMany("Webpages")
                        .HasForeignKey("TermIndexTerm");
                });
#pragma warning restore 612, 618
        }
    }
}
